CREATE TABLE TODOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    TODO VARCHAR(1000),
    DATE_OF_CREATION DATE,
    TO_BE_COMPLETED_BY DATE
);

INSERT INTO TODOS(TODO, DATE_OF_CREATION, TO_BE_COMPLETED_BY) VALUES("PYTHON PROJECT", "2024-02-15", "2024-02-18");

SELECT * FROM TODOS;
